### ISSUE TITLE
Showcase 

### ISSUE THREAD

**Issue by ma-sonr** [sonr-io/docs#50]
**Is your feature request related to a problem? Please describe.**
Please describe the problem you are trying to solve.

It would be helpful for developers to see a showcase of all the Sonr applications that have been built! 

**Describe the solution you'd like**
Please describe the desired behavior.

- awesome-sonr repo 
- https://docusaurus.io/showcase

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

**Comment by prnk28** [comment]
This should now be under https://community.sonr.io

**Comment by ma-sonr** [comment]
i agree
will close
